#!/usr/bin/env bash
# Install Nginx on remote server

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello world" > /var/www/html/index.html
sudo service nginx start
