#!/usr/bin/env bash
# Install nginx web server

sudo apt-get update
sudo apt-get install -y nginx
chown -R "$USER":"$USER" /var/www/html
echo "Hello World!" > /var/www/html/index.nginx-debian.html
line="\\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
sed -i "26i $line" /etc/nginx/sites-available/default
sudo service nginx restart
