#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get update
sudo apt-get install software-properties-common -y
sudo apt-get-repository ppa:vbernat/haproxy-2.5 -y
sudo apt-get update
sudo apt-get install haproxy -y
echo "frontend web-front
     	bind *:80
	default_backend web-backend

backend web-backend
	balance roundrobin
	server web1 107.22.146.121:80 check
	server web2 52.91.133.213:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start
