#!/usr/bin/env bash
# The script loops from 1 to 10 and:
# Displays "bad luck" for the 4th iteration
# Displays "good luck" for the 8th iteration
# Displays "Best School" for the rest

i=0

while [ $i -lt 10 ]
do
	if [ $i -eq 3 ]
	then
		echo "bad luck"
	elif [ $i -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( i++ ))
done	
