#!/usr/bin/env bash

# Fixe Nginx so that it should be runnig as nginx user
sudo apt-get install nginx -y
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/defaut
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
